addSbtPlugin("org.foundweekends" % "sbt-bintray"           % "0.5.4")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"               % "1.0.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"            % "5.2.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"   % "1.3.25")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"          % "2.0.2")
addSbtPlugin("com.dwijnand"      % "sbt-travisci"          % "1.2.0")
addSbtPlugin("com.typesafe.play" % "sbt-plugin"            % "2.7.3")
